hubbleprotocol/scope

configs/devnet/hubble.json
configs/mainnet/hubble.json

Open question: shall we remove yitoken completely?

:wrench: Remove UST from the configuration

---

configs/devnet/hubble.json
configs/mainnet/hubble.json
off_chain/docker-bot/helm/values.yaml

- Add DaoSOL to hubble price feed.
- Update bot config to include the configuration file.

:wrench: Add DaoSOL to hubble price feed.

---

configs/mainnet/hubble.json
off_chain/docker-bot/helm/values.yaml
off_chain/scope-cli/src/main.rs
off_chain/scope-cli/src/scope_client.rs
programs/scope/src/handlers/handler_refresh_prices.rs
tests/bot_utils.ts
tests/test_crank.ts

- Log errors only if some prices are still too old after 3 refresh attempts
- Log all prices after each refresh
- Force refresh every 20s even if prices appear to be fresh (try to avoid RPC clock penalty)

Change logs strategy and force refresh at least every 20s

---

programs/scope/src/utils/pyth.rs

Just add more logs to better identify the source of an invalid price.

:loud_sound: Add more logs to pyth price validation

---

configs/devnet/hubble.json
configs/mainnet/hubble.json

Note: devnet conf for daoSOL is actually using scnSOL account as I don't have a daoSOL reserve on devnet. I just want the price to be consistent around ~1 SOL

:wrench: DaoSOL through splStake and add USDC

---

configs/devnet/hubble.json
configs/mainnet/hubble.json
off_chain/scope-cli/src/scope_client.rs

Add cUSDC, cORCA, cSLND, cSRM, cRAY, cFTT and cSTSOL

:dizzy: Add ctokens from the main pool

---

configs/mainnet/hubble.json
off_chain/scope-cli/src/scope_client.rs

Bonus: Increase max age for DAI as current feed rate is 240s

Color price age depending if too old or not

---

configs/devnet/hubble.json
configs/mainnet/hubble.json

Bonus: Increase default max age report for fewer alerts.

🔧 Change DAI source from switchboard to Pyth

---

Makefile
configs/mainnet/hubble.json

We don't control current BTC feed

Change BTC price feed

---

configs/mainnet/hubble.json
third-party/switchboard/feeds/msol-usd.json
third-party/switchboard/feeds/sol-usd.json
third-party/switchboard/feeds/stsol-usd.json
third-party/switchboard/feeds/usdc-usd.json
third-party/switchboard/feeds/usdt-usd.json
third-party/switchboard/switchboard-test.sh

- USDT/USD (bound) - https://switchboard.xyz/explorer/3/8KCm1o99ZvhZBiFfsDpSK4EC6iDeqS5NkxQtaCigQTqB
- USDC/USD (bound) - https://switchboard.xyz/explorer/3/DZxQcTQnNMskQ2VEX57jNW1rBpLTVEVcDYySFkhDaLCe
- SOL/USD - https://switchboard.xyz/explorer/3/4aUbjcFqQNxMVjsgnuxAAmtPZHyyZBsLeJjBM8LYrkFX
- mSOL/USD (bound) - https://switchboard.xyz/explorer/3/856a1KbnQa7gWzaqmjaYWWAGqcqegZxmaatRig3hzfv9
- stSOL/USD (bound) - https://switchboard.xyz/explorer/3/AMtCwAExNkNiFFMF7QCDA2RqbWi816K7woQq8KB6emHj

Add mSOL and stSOL swtichboard v2 oracles

---

configs/mainnet/hubble.json
third-party/switchboard/feeds/msol-usd-1hr-twap.json
third-party/switchboard/feeds/stsol-usd-1hr-twap.json

- mSOL - https://switchboard.xyz/explorer/3/H8BUVDG7hBbBacPbv3QM6cH3iqJ6kMdpJF9HnaPHKRyn 
- stSOL - https://switchboard.xyz/explorer/3/9NxKa8tjkyVyCEf42HnepyLzbN2ZrY4ebzoqF6jGAb6s

Add mSOL and stSOL switchboard twap feeds

---

configs/mainnet/hubble.json
third-party/switchboard/feeds/msol-usd-1hr-twap.json
third-party/switchboard/feeds/msol-usd.json
third-party/switchboard/feeds/stsol-usd-1hr-twap.json
third-party/switchboard/feeds/stsol-usd.json

Add new mSOL and stSOL feeds with a reference to new SOL/USD feed - https://switchboard.xyz/explorer/3/4aUbjcFqQNxMVjsgnuxAAmtPZHyyZBsLeJjBM8LYrkFX

Fix mSOL and stSOL feeds - reference new SOL/USD price feed

---

configs/mainnet/hubble.json

Undo: 
https://github.com/hubbleprotocol/scope/commit/65da2e263d4717a47142206ec965aa1c16434ac8#diff-75f4835e41b8e4c3b76ed9ca00b599355b0d4c6dcbe0183a7759b4738cd96ecf
Because error is:
```
2022-12-28T11:42:12.098033Z ERROR liquidations_bot::liquidation: try_liquidate_cash_based::error error=Client(Rpc error on send transaction: RpcError(
RpcResponseError {
code: -32002,
message: "Transaction simulation failed: Error processing Instruction 1: custom program error: 0x179b",
data: SendTransactionPreflightFailure(
RpcSimulateTransactionResult {
err: Some(
InstructionError(
1,
Custom(
6043,
),
),
),
logs: Some(
[
"Program ComputeBudget111111111111111111111111111111 invoke [1]",
"Program ComputeBudget111111111111111111111111111111 success",
"Program HubbLeXBb7qyLHt3x7gvYaRrxQmmgExb7fCJgDqFuB6T …
```

Add FTT ema back

---

configs/devnet/hubble.json
configs/mainnet/hubble.json

Note: FTT EMA was already restored in #106

Add back FTT and SRM

---

README.md
off_chain/scope-cli/src/main.rs
off_chain/scope-cli/src/scope_client.rs

Add dynamic precision

---

Makefile
configs/devnet/hubble.json
configs/mainnet/hubble.json
off_chain/scope-cli/src/main.rs
off_chain/scope-cli/src/scope_client.rs
off_chain/scope-cli/src/web/routes.rs
programs/scope/src/oracles/spl_stake.rs
third-party/switchboard/feeds/samo-usd.json

Add SAMO, bSOL, laineSOL and multiple perf improvement.

---

.github/workflows/prettier.yml
.github/workflows/rust.yml
.rustfmt.toml
Cargo.lock
programs/scope/Cargo.toml
programs/scope/src/lib.rs
programs/scope/src/oracles/ctokens.rs
programs/scope/tests/common/fixtures.rs
programs/scope/tests/common/mock_oracles/mod.rs
programs/scope/tests/common/mock_oracles/pyth.rs
programs/scope/tests/common/mock_oracles/switchboard_v2.rs
programs/scope/tests/common/mod.rs
programs/scope/tests/common/runner.rs
programs/scope/tests/common/setup.rs
programs/scope/tests/common/types.rs
programs/scope/tests/common/utils.rs
programs/scope/tests/tests_security_init.rs
programs/scope/tests/tests_security_refresh_list.rs
programs/scope/tests/tests_security_refresh_one.rs
programs/scope/tests/tests_security_update_mapping.rs

- Add basic structure for "banks_client" style of tests but run them natively (not test-bpf)
- Use these tools to add security tests for all ixs

Introduce security tests

---

configs/devnet/hubble.json
configs/mainnet/hubble.json
third-party/switchboard/feeds/usdc-usd.json
third-party/switchboard/feeds/usdt-usd.json

- Add MNDE Twap
- Remove lower bounds of stablecoins

Add MNDE Twap, Remove lower bounds

---

docs/release_0.3.1.md

Main change is the introduction of protections against price refresh in flash loans and CPIs.

🔖 Release 0.3.1

---

configs/devnet/hubble.json
configs/mainnet/hubble.json
third-party/switchboard/feeds/chai-usd.json

- [] todo: create Swittchboard feeds for Chai after approval and replace the pubkeys in main config after oracle creation

add Style TWAP + Chai 

---

configs/mainnet/hubble.json
third-party/switchboard/feeds/hades-usd.json
third-party/switchboard/feeds/wsteth-usd.json

Bonus: remove obsolete jobs from HADES feed.

Update wsteth to switchboard

---

Cargo.lock
README.md
off_chain/scope-cli/src/oracle_helpers/ktokens.rs
off_chain/scope-cli/src/scope_client.rs
programs/scope/Cargo.toml
programs/scope/src/handlers/handler_refresh_prices.rs
programs/scope/src/oracles/ktokens/kamino.rs
programs/scope/src/oracles/ktokens/mod.rs
programs/scope/src/utils/mod.rs
programs/scope/src/utils/scope_chain.rs
programs/scope/tests/common/fixtures.rs
programs/scope/tests/common/mock_oracles/ktoken.rs
programs/scope/tests/common/mock_oracles/mod.rs
programs/scope/tests/common/mod.rs
programs/scope/tests/common/operations.rs
programs/scope/tests/common/utils.rs
programs/scope/tests/tests_security_refresh_list.rs
programs/scope/tests/tests_security_refresh_one.rs
programs/scope/tests/tests_security_update_mapping.rs

Calculate kToken price with Kamino `CollateralInfos` account rather than `ScopeChain`

---

docs/release_0.6.0.md
programs/scope/src/oracles/msol_stake.rs

Release 0.6.0 

---

docs/release_0.8.0.md
off_chain/scope-cli/src/scope_client.rs
programs/scope/src/lib.rs
programs/scope/types/src/lib.rs

Include minor fixes to first init of twaps account
* Fixes for twap impl by @oeble in <https://github.com/hubbleprotocol/scope/pull/180>
* Release  0.7.0 by @oeble in <https://github.com/hubbleprotocol/scope/pull/178>
* Scope twap by @silviutroscot in <https://github.com/hubbleprotocol/scope/pull/179>
**Full Changelog**: <https://github.com/hubbleprotocol/scope/compare/release/v0.7.0...release/v0.8.0>

(Devnet) Release 0.8.0

---

Cargo.lock
configs/mainnet/hubble.json
off_chain/scope-cli/src/oracle_helpers/meteora_dlmm.rs
off_chain/scope-cli/src/oracle_helpers/mod.rs
programs/lb-clmm-itf/Cargo.toml
programs/lb-clmm-itf/src/lib.rs
programs/lb-clmm-itf/src/u64x64_math.rs
programs/scope/Cargo.toml
programs/scope/src/oracles/ktokens_token_x.rs
programs/scope/src/oracles/meteora_dlmm.rs
programs/scope/src/oracles/mod.rs
programs/scope/src/utils/math.rs
programs/scope/tests/common/utils.rs

Tests will be added in a follow-up

Dlmm prices

---

off_chain/docker-bot/Dockerfile

Upstreamed in https://github.com/LukeMathWalker/cargo-chef/pull/247

Remove patched cargo chef install from docker build
